from . import model_product_whitelist
from . import model_product_blacklist
from . import bananas_backend
from . import binding
from . import res_partner
from . import product_product
from . import sale_order
from . import product_pricelist
from . import product_whitelist
from . import product_blacklist
